// TermsConditionsScreen.tsx
import { useNavigation } from "@react-navigation/native";
import { ArrowLeft } from "lucide-react-native";
import React from "react";
import { View, Text, ScrollView, StyleSheet, TouchableOpacity } from "react-native";

const TermsConditionsScreen = () => {
    const navigation = useNavigation();
    return (
        <View style={styles.container}>
            {/* Header */}
            <View style={{ flexDirection: "row", gap: 20, alignItems: "center" }}>
                <TouchableOpacity onPress={() => navigation.goBack()}>
                    <ArrowLeft size={24} color="#111827" />
                </TouchableOpacity>
                <View>
                    <Text style={styles.title}>Terms & Conditions</Text>
                    <Text style={styles.subTitle}>
                        Sttribe - Ebirtts Technologies Private Limited
                    </Text>
                </View>
            </View>

            <ScrollView style={styles.scrollView} showsVerticalScrollIndicator={false}>
                <Text style={styles.sectionText}>
                    This document is an electronic record in terms of Information
                    Technology Act, 2000 and rules there under as applicable and the
                    amended provisions pertaining to electronic records in various
                    statutes as amended by the Information Technology Act, 2000. This
                    electronic record is generated by a computer system and does not
                    require any physical or digital signatures.
                </Text>

                <Text style={styles.sectionHeader}>1. Acceptance of Terms</Text>
                <Text style={styles.sectionText}>
                    By accessing and using Sttribe ("the Service"), operated by Ebirtts
                    Technologies Private Limited ("Company", "we", "us", or "our"), you
                    accept and agree to be bound by the terms and provision of this
                    agreement.
                </Text>

                <Text style={styles.sectionHeader}>2. Service Description</Text>
                <Text style={styles.sectionText}>
                    Sttribe is a subscription sharing platform that enables users to
                    create tribes (groups) with family and friends to share OTT
                    (Over-The-Top) streaming service subscriptions, split costs, and
                    communicate through integrated features.
                </Text>

                <Text style={styles.sectionHeader}>3. User Responsibilities</Text>
                <Text style={styles.sectionText}>
                    • You must be at least 18 years old to use this service{"\n"}
                    • You are responsible for maintaining the confidentiality of your
                    account credentials{"\n"}
                    • You agree to provide accurate and current information{"\n"}
                    • You will not use the service for any unlawful or prohibited
                    activities{"\n"}
                    • You are responsible for all activities that occur under your
                    account
                </Text>

                <Text style={styles.sectionHeader}>4. Subscription Sharing</Text>
                <Text style={styles.sectionText}>
                    Our platform facilitates legitimate subscription sharing among
                    family and friends. Users must ensure they comply with the terms of
                    service of the respective OTT platforms. We do not encourage or
                    facilitate any violation of third-party terms of service.
                </Text>

                <Text style={styles.sectionHeader}>5. Payment Terms</Text>
                <Text style={styles.sectionText}>
                    • Payments are processed through secure third-party payment
                    gateways{"\n"}
                    • All fees are non-refundable unless otherwise specified{"\n"}
                    • Users are responsible for their share of subscription costs{"\n"}
                    • Late payment may result in suspension of service access
                </Text>

                <Text style={styles.sectionHeader}>6. Privacy and Data Protection</Text>
                <Text style={styles.sectionText}>
                    Your privacy is important to us. Please review our Privacy Policy,
                    which also governs your use of the Service, to understand our
                    practices regarding the collection, use, and disclosure of your
                    personal information.
                </Text>

                <Text style={styles.sectionHeader}>7. Intellectual Property</Text>
                <Text style={styles.sectionText}>
                    The Service and its original content, features, and functionality
                    are and will remain the exclusive property of Ebirtts Technologies
                    Private Limited and its licensors. The Service is protected by
                    copyright, trademark, and other laws.
                </Text>

                <Text style={styles.sectionHeader}>8. Termination</Text>
                <Text style={styles.sectionText}>
                    We may terminate or suspend your account and bar access to the
                    Service immediately, without prior notice or liability, under our
                    sole discretion, for any reason whatsoever and without limitation,
                    including but not limited to a breach of the Terms.
                </Text>

                <Text style={styles.sectionHeader}>9. Limitation of Liability</Text>
                <Text style={styles.sectionText}>
                    In no event shall Ebirtts Technologies Private Limited, nor its
                    directors, employees, partners, agents, suppliers, or affiliates, be
                    liable for any indirect, incidental, special, consequential, or
                    punitive damages, including without limitation, loss of profits,
                    data, use, goodwill, or other intangible losses.
                </Text>

                <Text style={styles.sectionHeader}>10. Governing Law</Text>
                <Text style={styles.sectionText}>
                    These Terms shall be interpreted and governed by the laws of India.
                    Any disputes arising under or in connection with these Terms shall
                    be subject to the exclusive jurisdiction of the courts in Bangalore,
                    Karnataka, India.
                </Text>

                <Text style={styles.sectionHeader}>11. Changes to Terms</Text>
                <Text style={styles.sectionText}>
                    We reserve the right, at our sole discretion, to modify or replace
                    these Terms at any time. If a revision is material, we will provide
                    at least 30 days' notice prior to any new terms taking effect.
                </Text>

                <Text style={styles.sectionHeader}>12. Contact Information</Text>
                <Text style={styles.sectionText}>
                    Ebirtts Technologies Private Limited{"\n"}
                    Email: support@sttribe.com{"\n"}
                    Website: https://sttribe.com
                </Text>

                <Text style={styles.footer}>Last updated: June 14, 2025</Text>
            </ScrollView>
        </View>
    );
};

export default TermsConditionsScreen;

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#fff",
        paddingHorizontal: 16,
        paddingTop: 20,
    },
    title: {
        fontSize: 22,
        fontWeight: "700",
        color: "#1f2937",
        marginBottom: 4,
        textAlign:'center'

    },
    subTitle: {
        fontSize: 16,
        fontWeight: "500",
        color: "#6b7280",
        marginBottom: 12,
        textAlign:'center'
    },
    scrollView: {
        marginTop: 10,
    },
    sectionHeader: {
        fontSize: 18,
        fontWeight: "600",
        color: "#111827",
        marginTop: 16,
        marginBottom: 6,
    },
    sectionText: {
        fontSize: 15,
        lineHeight: 22,
        color: "#374151",
        marginBottom: 10,
    },
    footer: {
        fontSize: 13,
        color: "#6b7280",
        marginTop: 20,
        marginBottom: 40,
        textAlign: "center",
    },
});
